### ISSUE TITLE
onBackgroundMessage

### ISSUE THREAD

**Issue by FrederickKiffen** [nextbss/flutter-push-notification#35]
when I receive the notification in onResume mode and select the message, when opening the app the message value is null, only the data value is non-null

**Comment by Henry-Keys** [comment]
Hello Kiffen, this is intended by design. In Android, when you tap a notification, only the notification data is passed to the opened Activity.

See the table in https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages.

**Comment by Henry-Keys** [comment]
> when I receive the notification in onResume mode and select the message, when opening the app the message value is null, only the data value is non-null

That's why that on *onResume* we check first if notification is not null. It will only be non-null if you receive the notification while the app is in the foreground.
```dart
plugin.setup(
  onResume: (notification, data) {
    if (notification != null) {
        // This is not null on Android when the notification is received while the app is in foreground
    }
  }
)
```
plugin.setup()
